
version: '3'

services:
 

  golang-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1304:1304"
    depends_on:
      - postgres-database

  postgres-database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}