apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafay-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rafay-app
  template:
    metadata:
      labels:
        app: rafay-app
    spec:
      containers:
      - name: rehan-app
        image: rehanafridi/rafay-app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1304
        resources:
          limits:
            cpu: "500m"    
            memory: "256Mi"  
          requests:
            cpu: "250m"    
            memory: "128Mi"  
        livenessProbe:
          httpGet:
            path: /health
            port: 1304
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 1304
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
