apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chatroom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-chatroom
  template:
    metadata:
      labels:
        app: go-chatroom
    spec:
      containers:
      - name: go-chatroom
        image: rehanafridi/go-chatroom:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1304
        readinessProbe:
          httpGet:
            path: /readiness
            port: 1304
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 1304
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
